name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Run Docker Build'
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-api:${{ github.run_number }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-api:${{ github.run_number }}
        docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-api:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-api:latest

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-api:${{ github.run_number }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: aci-simple-api
        location: 'east us 2'

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}latest
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-api:latest
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: aci-simple-api
        location: 'east us 2'